


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/uniread?useSSL=false&serverTimezone=UTC
    username: emmanuel
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


client:
  url: http://localhost:5173

logging:
  level:
    org:
      springframework:
        security: WARN