


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/uniread
    username: postgres
    password: 12345678

    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

client:
  url: http://localhost:5173


security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b